server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_DB
    username: postgres
    password: Ambroise3108
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
